# Generated by Django 4.2.3 on 2023-07-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cashflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("INCOME", "Income"), ("EXPENSE", "Expense")],
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SALARY", "Salary"),
                            ("REGULAR_BILL", "Regular Bill"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
