# Generated by Django 4.2.3 on 2023-07-18 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cashflows", "0002_alter_cashflow_source_alter_cashflow_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflow",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=9,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
