# Generated by Django 4.2.3 on 2023-07-21 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cashflows", "0004_alter_cashflow_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashflow",
            name="type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                default=None,
                max_length=10,
            ),
        ),
    ]
